### ISSUE TITLE
vit_base_MSMT17 only achive 70.1%

### ISSUE THREAD

**Issue by shorelake** [CASIA-IVA-Lab/PASS-reID#1]
Hi, thanks for your awesome work.
I met some problem when trying to reproduce the results of vit-base on MSMT17. all default settings were not changed. I only got 70.1% mAP and 87.3% Rank1 that results is far lower than your reported, 71.8% mAP and 88.2% Rank1.
I have tried 3 times.

My env: torch1.10.0+cu111, others is the same as requirements.txt
GPU: NVIDIA GeForce RTX 3090
OS: ubuntu1~18.04.1
logs:[train_log.txt](https://github.com/CASIA-IVA-Lab/PASS-reID/files/8477913/train_log.txt)

**Comment by zhukuan96** [comment]
I am not clear, but you can try: (1) using torch1.8, because the transreid recommand to use torch1.8 (2) how many GPUs did you use? Using single GPU to train.

How about the results you reproduced on market and vit-s?

**Comment by shorelake** [comment]
I found the cause of the problem, I used the dataset MSMT17_v2, now I change it to MSMT17_V1 and the paper results can be  successfully reproduced

**Comment by zhukuan96** [comment]
Thank you.

**Comment by 1677125138** [comment]
I complete train and test with market1501 dataset.
But I don't know how to show result : query and gallery example , so can you help me?
thank you so much!
